---
title: "Untitled"
output: html_document
date: "2022-10-03"
---
```{r}
library(vcfR)
library(related)
```

```{r}
vcf = read.vcfR('C:/Users/parsonsee/Desktop/nomiss.vcf')

geno = extract.gt(vcf)
G_relate = matrix(NA, nrow = ncol(geno), ncol = nrow(geno)*2)
abob = t(substr(geno, start = 1, stop = 1))
bbob = t(substr(geno, start = 3, stop = 3))
odd = seq(1, ncol(G_relate), by = 2)
G_relate[, odd] = abob
G_relate[, odd + 1] = bbob
rownames(G_relate) = rownames(abob)
colnames(G_relate) = rep(colnames(abob), each = 2)
class(G_relate) = "numeric"
G_relate = data.frame(Individual = rownames(G_relate), G_relate)
G_relate$Individual = as.character(G_relate$Individual)
G_relate[, 2:ncol(G_relate)] = G_relate[, 2:ncol(G_relate)] + 1 #to avoid 0s in data
```

```{r}
relat_fullDat = coancestry(G_relate, wang=1, lynchli=1)
```

# write for delta7, delta8, relatedness, and inbreeding 


```{r}
write.csv(relat_fullDat$delta8, file = "C:/Users/parsonsee/Desktop/delta8_nomiss.csv")
write.csv(relat_fullDat$delta7, file = "C:/Users/parsonsee/Desktop/delta7_nomiss.csv")
write.csv(relat_fullDat$inbreeding, file = "C:/Users/parsonsee/Desktop/inbreeding_nomiss.csv")
write.csv(relat_fullDat$relatedness, file = "C:/Users/parsonsee/Desktop/relatedness_nomiss.csv")
```

